apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironic
spec:
  template:
    spec:
      containers:
      - name: ironic
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-password
              key: password
        - name: IRONIC_USE_MARIADB
          value: "true"
        - name: IRONIC_EXPOSE_JSON_RPC
          value: "true"
        - name: IRONIC_REVERSE_PROXY_SETUP
          value: "true"
        volumeMounts:
        - name: cert-mariadb-ca
          mountPath: "/certs/ca/mariadb"
          readOnly: true
      - name: ironic-httpd
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-password
              key: password
        - name: IRONIC_USE_MARIADB
          value: "true"
        - name: IRONIC_EXPOSE_JSON_RPC
          value: "true"
        - name: IRONIC_REVERSE_PROXY_SETUP
          value: "true"
        volumeMounts:
        - name: cert-mariadb-ca
          mountPath: "/certs/ca/mariadb"
          readOnly: true
      volumes:
      - name: cert-mariadb
        secret:
          secretName: mariadb-cert
      - name: cert-mariadb-ca
        secret:
          secretName: ironic-cacert
