apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- ../basic-auth_tls

configMapGenerator:
- name: ironic
  behavior: create
  envs:
  - ironic.env

patches:
- patch: |
    # Don't try to pull again the pre-loaded image
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
  target:
    kind: Deployment
    name: controller-manager
- patch: |
    # Add a namespace to watch
    - op: replace
      path: /kind
      value: RoleBinding
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: baremetal-operator-manager-rolebinding
- patch: |
    # Add a namespace to watch
    - op: replace
      path: /kind
      value: Role
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: baremetal-operator-manager-role
- path: namespaced-manager-patch.yaml
- patch: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: baremetal-operator-manager-rolebinding
    roleRef:
      kind: Role
      name: baremetal-operator-manager-role
    subjects:
    - kind: ServiceAccount
      name: baremetal-operator-controller-manager
      namespace: baremetal-operator-system

images:
- name: quay.io/metal3-io/baremetal-operator
  newTag: e2e

# We cannot use suffix hashes since the kustomizations we build on
# cannot be aware of what suffixes we add.
generatorOptions:
  disableNameSuffixHash: true

# NOTE: These credentials are generated automatically in hack/ci-e2e.sh
secretGenerator:
- name: ironic-credentials
  files:
  - username=ironic-username
  - password=ironic-password

transformers:
- roles-ns-annotator.yaml
