apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../basic-auth_tls
- ./automated-cleaning
- ./basic-ops
- ./external-inspection
- ./externally-provisioned
- ./inspection
- ./live-iso-ops
- ./provisioning-ops
- ./re-inspection
- ./upgrade-bmo
- ./upgrade-ironic

components:
    - ../../components/namespace-scoped

configMapGenerator:
- name: ironic
  namespace: baremetal-operator-system
  behavior: create
  envs:
  - ironic.env

patches:
- patch: |
    # Don't try to pull again the pre-loaded image
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
  target:
    kind: Deployment
    name: controller-manager
- path: ./namespaced-manager-patch.yaml

images:
- name: quay.io/metal3-io/baremetal-operator
  newTag: e2e

# We cannot use suffix hashes since the kustomizations we build on
# cannot be aware of what suffixes we add.
generatorOptions:
  disableNameSuffixHash: true

# NOTE: These credentials are generated automatically in hack/ci-e2e.sh
secretGenerator:
- name: ironic-credentials
  namespace: baremetal-operator-system
  files:
  - username=ironic-username
  - password=ironic-password
