apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
# Remove ClusterRoleBinding (namespace scoped mode)
- patch: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: baremetal-operator-manager-rolebinding
    $patch: delete
# Remove ClusterRole (namespace scoped mode)
- patch: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: baremetal-operator-manager-role
    $patch: delete
