apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironic
spec:
  template:
    spec:
      containers:
      - name: ironic
        envFrom:
        # This is the htpassword matching the ironic-auth-config
        - secretRef:
            name: ironic-htpasswd
        - configMapRef:
            name: ironic-bmo-configmap
      volumes:
      - name: ironic-auth-config
        secret:
          secretName: ironic-auth-config
