name: E2E Test

on:
  workflow_call:
    inputs:
      bmc-protocol:
        required: true
        type: string
      runner:
        type: string
        default: "equinix-4cpu-16gb"
      ginkgo-focus:
        type: string
        default: ""
      ref:
        type: string
        default: ${{ github.ref }}

permissions: {}

jobs:
  test:
    name: E2E test
    runs-on: ${{ inputs.runner }}

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        ref: ${{ inputs.ref }}

    - name: Install libvirt
      run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-daemon-system qemu-kvm virt-manager libvirt-dev
          sudo systemctl enable libvirtd
          sudo systemctl start libvirtd

    - name: Run BMO e2e Tests
      env:
        BMC_PROTOCOL: ${{ inputs.bmc-protocol }}
        GINKGO_FOCUS: "${{ inputs.ginkgo-focus }}"
      # We need a new shell to pick up the new group. That is why we do the sudo -s -u $USER ...
      # Remove the pre-installed go version. We install the exact version we need.
      run: |
        echo $USER
        env
        cat /etc/os-release
        sudo usermod -a -G libvirt $(whoami)
        sudo -s -u $(whoami) --preserve-env bash ${{ github.workspace }}/hack/ci-e2e.sh

    - name: Upload artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: artifacts-${{ inputs.bmc-protocol }}.tar.gz
        path: test/e2e/_artifacts
        if-no-files-found: error
        overwrite: false
