name: E2E Test pipeline

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    branches:
    - 'main'
    - 'release-*'
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
    - '.gitignore'
    - 'LICENSE'
    - 'SECURITY_CONTACTS'
    - 'DCO'
    - 'OWNERS'

permissions: {}

jobs:
  golangci-lint:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/golangci-lint.yml

  unit:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/unit.yml

  e2e-fixture-test:
    needs: [golangci-lint, unit]
    uses: ./.github/workflows/e2e-fixture-test.yml

  e2e-test:
    needs: [golangci-lint, unit]
    strategy:
      # Avoid wasting CI resources
      fail-fast: true
      matrix:
        bmc-protocol:
        - redfish-virtualmedia
        # TODO(lentzi90): Enable again when https://github.com/metal3-io/baremetal-operator/issues/2456 is fixed.
        # - ipmi
    uses: ./.github/workflows/e2e-test.yml
    with:
      bmc-protocol: ${{ matrix.bmc-protocol }}
